// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt5p9jvC0SNBi21birwiMczx1M-__JqZ0',
    appId: '1:290144668749:web:ab05ee55ce470f29c5a004',
    messagingSenderId: '290144668749',
    projectId: 'fruit-hub-60fba',
    authDomain: 'fruit-hub-60fba.firebaseapp.com',
    storageBucket: 'fruit-hub-60fba.firebasestorage.app',
    measurementId: 'G-WHD4CNNSFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAumfeNrIsMs4WRCBSEQO04814wI8Wy8I',
    appId: '1:290144668749:android:d12212cd4857e79fc5a004',
    messagingSenderId: '290144668749',
    projectId: 'fruit-hub-60fba',
    storageBucket: 'fruit-hub-60fba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe773peKNwEkjfNfR8y71wFxKWZNApt80',
    appId: '1:290144668749:ios:386d0259ddab9fa8c5a004',
    messagingSenderId: '290144668749',
    projectId: 'fruit-hub-60fba',
    storageBucket: 'fruit-hub-60fba.firebasestorage.app',
    iosBundleId: 'com.example.fruithub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe773peKNwEkjfNfR8y71wFxKWZNApt80',
    appId: '1:290144668749:ios:386d0259ddab9fa8c5a004',
    messagingSenderId: '290144668749',
    projectId: 'fruit-hub-60fba',
    storageBucket: 'fruit-hub-60fba.firebasestorage.app',
    iosBundleId: 'com.example.fruithub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt5p9jvC0SNBi21birwiMczx1M-__JqZ0',
    appId: '1:290144668749:web:363fd303647f9419c5a004',
    messagingSenderId: '290144668749',
    projectId: 'fruit-hub-60fba',
    authDomain: 'fruit-hub-60fba.firebaseapp.com',
    storageBucket: 'fruit-hub-60fba.firebasestorage.app',
    measurementId: 'G-0J1TC6LS8E',
  );
}
